AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 -> Lambda grayscale -> S3 (same bucket), loop prevention, no circular deps.

Parameters:
  BucketName:
    Type: String
    Description: Globally unique bucket used for both input (incoming/) and output (grayscale/).
    MinLength: 3
    MaxLength: 63
    AllowedPattern: '^[a-z0-9][a-z0-9\.-]{1,61}[a-z0-9]$'
    ConstraintDescription: must be a valid S3 bucket name (lowercase letters, numbers, dots, and hyphens).

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 256
    Architectures: [x86_64]

Resources:
  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  GrayscaleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          INPUT_PREFIX: incoming/
          OUTPUT_PREFIX: grayscale/
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref BucketName
        - S3WritePolicy:
            BucketName: !Ref BucketName
      Events:
        ImageUpload:
          Type: S3
          Properties:
            Bucket: !Ref ImagesBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: incoming/
                  - Name: suffix
                    Value: .png

Outputs:
  BucketName:
    Value: !Ref BucketName
